### ISSUE TITLE
CSRF mismatch when attempting to create media

### ISSUE THREAD

**Issue by mikeheft** [WeInfuse/redox#28]
>Rails version 6.1.1
Ruby version 3.0.0
Redox Gem version 1.6.0

I'm running into issue when attempting to create a media request/model. I found the `media_upload_test` and `media_test` and am attempting to follow that flow. I am receiving `'CSRF mismatch'` errors in the response from `Redox::Request::Media.create`. Not really sure what's going on here as I can't find any reference to any issue of this kind online/stack overflow.

```ruby
meta = Redox::Models::Meta.new
meta.set_source(name: 'Source', id: '<ID>')
meta.add_destination(name: 'Destination', id: '<ID>')

media = Redox::Models::Media.new(meta: meta)
media.update(patient: patient_details)
media.update(visit: visit_details)
media_stuff = {
  file_type: 'PDF', file_name: 'SamplePDF STUFF',
  file_contents: Base64.encode64(params[:file].path),
  document_type: 'Testing STUFF', document_id: '1'
}

media.update(media: media_stuff)
media_upload = Redox::Models::MediaUpload.new(media)
Redox::Request::Media.create(media_upload, meta: meta)
```
have also tried this 👇 but still receiving same error
```ruby
meta = Redox::Models::Meta.new
meta.set_source(name: 'Source', id: '<ID>')
meta.add_destination(name: 'dest', id: '<ID>')

media = Redox::Models::MediaUpload.new
media.update(meta: meta)
media.update(patient: order.patient_details)
media.update(visit: order.visit_details)
media_stuff = {
  file_type: 'PDF', file_name: 'SamplePDF STUFF',
  file_contents: Base64.encode64(params[:file].path),
  document_type: 'Testing STUFF', document_id: '1'
}
media.update(media: media_stuff)
Redox::Request::Media.create(media, meta: meta)
```

**Comment by mmcrockett** [comment]
First you may need to contact Redox for authentication information and then configure:
https://github.com/WeInfuse/redox#configuration

Next you will have access to Redox dashboard https://dashboard.redoxengine.com where you can get a real source and destination id (something like "0f4ed1d1-877d-4351-8cfd-ab1234b488d6")

Hope this helps you move forward!

**Comment by mikeheft** [comment]
Sorry, it does not. I followed those steps. I have my configuration set up correctly. I have 'real' sources and destinations. I merely anonymized them so as not to have the actual information on GitHub, even though it's only a test account for now

**Comment by mmcrockett** [comment]
Sorry for misunderstanding - I wasn't sure how far along you were, I'll be working in the part of the code in the next week or so and will let you know anything I find. I know there is a difference in how you are supposed to handle > 200KB.

Now that I think about it I wonder if it's some change in how Rails 6 sends the type (or maybe HTTParty and Rails 6) because the CSRF error sounds like it's not hitting a json endpoint correctly and that maybe it's hitting a regular html endpoint.

- Does the Redox dashboard show any errors?
- Does the response object returned show any more information?

**Comment by mikeheft** [comment]
Ya, my boss was wondering the same thing. I'm able to make successful requests creating the media object through the api using httpparty. I started with a very small pdf. Then once I had that down, I started on the blob endpoint for the larger files. I don't know if it's an interaction with Rails and httpparty; I'm able to make the requests successfully, just not with the gem. 

No there's no errors in redox dashboard. It doesn't send anything. And the response object returns as `{'response'=><HttPartyResponse>}` when accessing the response body, it gives ''CSRF mismatch".

**Comment by mmcrockett** [comment]
Well thanks for the insight. The media model was added recently by an outside contributor so I actually haven't worked with it yet but like I said it's scheduled to be looked at next sprint because we need to start using it soon!

Does `Redox::Authentication.new.authenticate` return a response that is valid or does it give same failure?

**Comment by mikeheft** [comment]
The `Redox::Authentication.new.authenticate` does return a `Redox::Authentication` response with the proper response attribute that has the accessToken, expires, refreshToken keys in the hash

**Comment by mmcrockett** [comment]
I created a Rails 6.1.3 app using ruby 3.0.0 on Ubuntu 20 with rbenv and was able to send the message to my development endpoint in Redox. I am using a _slightly_ newer gem version 1.6.1 that we should release in the next week that adds some helpers to the media model.

I did notice that you need a `media.provider = Redox::Models::OrderingProvider.new(id: '44557788')` which was not allowed in the 1.6.0 version (it would simply ignore this line)

It's pretty weird because even when I sent 'bad' messages while testing I still always got a reasonable error message, ie. Redox telling me the source was not valid or that the provider id was required. Wonder if there is any conflict in low-level http versions or maybe we're stomping on another gems namespace :shrug: ?

```
path = '/tmp/Screenshot_2021-03-02_12-21-28.png' # Just a rando screenshot I had
meta = {"EventDateTime"=>"2021-03-11T03:33:57.058577Z", "Test"=>true, "FacilityCode"=>nil, "Source"=>{"ID"=>"xxxxxx-xxxx-xxxx-xxxx", "Name"=>"mcrockett dev source"}, "Destinations"=>[{"ID"=>"yyyyyyy-yyy-yyy-yyyy", "Name"=>"Dev Media"}]}

media = Redox::Models::Media.new
raise 'File too big for base64 method' if File.size(path) > 200_000
media.file_contents = Base64::encode64(File.read(path))
media.file_type     = "#{File.extname(path)}".delete_prefix('.').upcase
media.file_name     = File.basename(path, '.*')
media.document_type = 'blah blah'
media.document_id   = 'abc1213'
media.availability = 'Available'

# not in 1.6.0 version
media.provider = Redox::Models::OrderingProvider.new(id: '44557788')

upload = Redox::Models::MediaUpload.new(
   patient: patientdata,
   visit: visitdata,
   media: media,
)

Redox::Request::Media.create(upload, meta: meta)
```

**Comment by mmcrockett** [comment]
Closing until we can recreate.
